[tool.towncrier]
name = "libasdf"
version = "0.1.0a2"
directory = "changes"
filename = "CHANGES.rst"
issue_format = "`#{issue} <https://github.com/asdf-format/asdf/issues/{issue}>`_"
wrap = true

[[tool.towncrier.type]]
name = "General"
[[tool.towncrier.type]]
name = "Feature"
[[tool.towncrier.type]]
name = "Bugfix"
[[tool.towncrier.type]]
name = "Documentation"
directory = "doc"
[[tool.towncrier.type]]
name = "Removal"
[[tool.towncrier.type]]
name = "Misc"
